// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subjects.proto

package axoom.subjects.v1;

public final class Subjects {
  private Subjects() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axoom.subjects.v1.Subject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The unique Subject ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     * The unique Subject ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * A name describing the Subject
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * A name describing the Subject
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * The Subject's Type
     * </pre>
     *
     * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
     */
    boolean hasSubjectType();
    /**
     * <pre>
     * The Subject's Type
     * </pre>
     *
     * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
     */
    axoom.subjects.v1.Subjects.SubjectType getSubjectType();
    /**
     * <pre>
     * The Subject's Type
     * </pre>
     *
     * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
     */
    axoom.subjects.v1.Subjects.SubjectTypeOrBuilder getSubjectTypeOrBuilder();

    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */
    int getLabelsCount();
    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */
    boolean containsLabels(
        java.lang.String key);
    /**
     * Use {@link #getLabelsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getLabels();
    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getLabelsMap();
    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */

    java.lang.String getLabelsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */

    java.lang.String getLabelsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code axoom.subjects.v1.Subject}
   */
  public  static final class Subject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:axoom.subjects.v1.Subject)
      SubjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subject.newBuilder() to construct.
    private Subject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subject() {
      id_ = "";
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Subject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              axoom.subjects.v1.Subjects.SubjectType.Builder subBuilder = null;
              if (subjectType_ != null) {
                subBuilder = subjectType_.toBuilder();
              }
              subjectType_ = input.readMessage(axoom.subjects.v1.Subjects.SubjectType.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subjectType_);
                subjectType_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                labels_ = com.google.protobuf.MapField.newMapField(
                    LabelsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              labels__ = input.readMessage(
                  LabelsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              labels_.getMutableMap().put(
                  labels__.getKey(), labels__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_Subject_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetLabels();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_Subject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              axoom.subjects.v1.Subjects.Subject.class, axoom.subjects.v1.Subjects.Subject.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * The unique Subject ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The unique Subject ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * A name describing the Subject
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * A name describing the Subject
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_TYPE_FIELD_NUMBER = 3;
    private axoom.subjects.v1.Subjects.SubjectType subjectType_;
    /**
     * <pre>
     * The Subject's Type
     * </pre>
     *
     * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
     */
    public boolean hasSubjectType() {
      return subjectType_ != null;
    }
    /**
     * <pre>
     * The Subject's Type
     * </pre>
     *
     * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
     */
    public axoom.subjects.v1.Subjects.SubjectType getSubjectType() {
      return subjectType_ == null ? axoom.subjects.v1.Subjects.SubjectType.getDefaultInstance() : subjectType_;
    }
    /**
     * <pre>
     * The Subject's Type
     * </pre>
     *
     * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
     */
    public axoom.subjects.v1.Subjects.SubjectTypeOrBuilder getSubjectTypeOrBuilder() {
      return getSubjectType();
    }

    public static final int LABELS_FIELD_NUMBER = 4;
    private static final class LabelsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_Subject_LabelsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> labels_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetLabels() {
      if (labels_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LabelsDefaultEntryHolder.defaultEntry);
      }
      return labels_;
    }

    public int getLabelsCount() {
      return internalGetLabels().getMap().size();
    }
    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */

    public boolean containsLabels(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetLabels().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLabelsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getLabels() {
      return getLabelsMap();
    }
    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getLabelsMap() {
      return internalGetLabels().getMap();
    }
    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */

    public java.lang.String getLabelsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLabels().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Additional free-form labels
     * </pre>
     *
     * <code>map&lt;string, string&gt; labels = 4;</code>
     */

    public java.lang.String getLabelsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLabels().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (subjectType_ != null) {
        output.writeMessage(3, getSubjectType());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetLabels(),
          LabelsDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (subjectType_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSubjectType());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetLabels().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        labels__ = LabelsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, labels__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof axoom.subjects.v1.Subjects.Subject)) {
        return super.equals(obj);
      }
      axoom.subjects.v1.Subjects.Subject other = (axoom.subjects.v1.Subjects.Subject) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (hasSubjectType() == other.hasSubjectType());
      if (hasSubjectType()) {
        result = result && getSubjectType()
            .equals(other.getSubjectType());
      }
      result = result && internalGetLabels().equals(
          other.internalGetLabels());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasSubjectType()) {
        hash = (37 * hash) + SUBJECT_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSubjectType().hashCode();
      }
      if (!internalGetLabels().getMap().isEmpty()) {
        hash = (37 * hash) + LABELS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetLabels().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static axoom.subjects.v1.Subjects.Subject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.Subject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static axoom.subjects.v1.Subjects.Subject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.subjects.v1.Subjects.Subject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(axoom.subjects.v1.Subjects.Subject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code axoom.subjects.v1.Subject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:axoom.subjects.v1.Subject)
        axoom.subjects.v1.Subjects.SubjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_Subject_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetLabels();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableLabels();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_Subject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                axoom.subjects.v1.Subjects.Subject.class, axoom.subjects.v1.Subjects.Subject.Builder.class);
      }

      // Construct using axoom.subjects.v1.Subjects.Subject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        if (subjectTypeBuilder_ == null) {
          subjectType_ = null;
        } else {
          subjectType_ = null;
          subjectTypeBuilder_ = null;
        }
        internalGetMutableLabels().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_Subject_descriptor;
      }

      public axoom.subjects.v1.Subjects.Subject getDefaultInstanceForType() {
        return axoom.subjects.v1.Subjects.Subject.getDefaultInstance();
      }

      public axoom.subjects.v1.Subjects.Subject build() {
        axoom.subjects.v1.Subjects.Subject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public axoom.subjects.v1.Subjects.Subject buildPartial() {
        axoom.subjects.v1.Subjects.Subject result = new axoom.subjects.v1.Subjects.Subject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (subjectTypeBuilder_ == null) {
          result.subjectType_ = subjectType_;
        } else {
          result.subjectType_ = subjectTypeBuilder_.build();
        }
        result.labels_ = internalGetLabels();
        result.labels_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof axoom.subjects.v1.Subjects.Subject) {
          return mergeFrom((axoom.subjects.v1.Subjects.Subject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(axoom.subjects.v1.Subjects.Subject other) {
        if (other == axoom.subjects.v1.Subjects.Subject.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSubjectType()) {
          mergeSubjectType(other.getSubjectType());
        }
        internalGetMutableLabels().mergeFrom(
            other.internalGetLabels());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        axoom.subjects.v1.Subjects.Subject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (axoom.subjects.v1.Subjects.Subject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * The unique Subject ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The unique Subject ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The unique Subject ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique Subject ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique Subject ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * A name describing the Subject
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A name describing the Subject
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A name describing the Subject
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A name describing the Subject
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A name describing the Subject
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private axoom.subjects.v1.Subjects.SubjectType subjectType_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          axoom.subjects.v1.Subjects.SubjectType, axoom.subjects.v1.Subjects.SubjectType.Builder, axoom.subjects.v1.Subjects.SubjectTypeOrBuilder> subjectTypeBuilder_;
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      public boolean hasSubjectType() {
        return subjectTypeBuilder_ != null || subjectType_ != null;
      }
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      public axoom.subjects.v1.Subjects.SubjectType getSubjectType() {
        if (subjectTypeBuilder_ == null) {
          return subjectType_ == null ? axoom.subjects.v1.Subjects.SubjectType.getDefaultInstance() : subjectType_;
        } else {
          return subjectTypeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      public Builder setSubjectType(axoom.subjects.v1.Subjects.SubjectType value) {
        if (subjectTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subjectType_ = value;
          onChanged();
        } else {
          subjectTypeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      public Builder setSubjectType(
          axoom.subjects.v1.Subjects.SubjectType.Builder builderForValue) {
        if (subjectTypeBuilder_ == null) {
          subjectType_ = builderForValue.build();
          onChanged();
        } else {
          subjectTypeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      public Builder mergeSubjectType(axoom.subjects.v1.Subjects.SubjectType value) {
        if (subjectTypeBuilder_ == null) {
          if (subjectType_ != null) {
            subjectType_ =
              axoom.subjects.v1.Subjects.SubjectType.newBuilder(subjectType_).mergeFrom(value).buildPartial();
          } else {
            subjectType_ = value;
          }
          onChanged();
        } else {
          subjectTypeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      public Builder clearSubjectType() {
        if (subjectTypeBuilder_ == null) {
          subjectType_ = null;
          onChanged();
        } else {
          subjectType_ = null;
          subjectTypeBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      public axoom.subjects.v1.Subjects.SubjectType.Builder getSubjectTypeBuilder() {
        
        onChanged();
        return getSubjectTypeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      public axoom.subjects.v1.Subjects.SubjectTypeOrBuilder getSubjectTypeOrBuilder() {
        if (subjectTypeBuilder_ != null) {
          return subjectTypeBuilder_.getMessageOrBuilder();
        } else {
          return subjectType_ == null ?
              axoom.subjects.v1.Subjects.SubjectType.getDefaultInstance() : subjectType_;
        }
      }
      /**
       * <pre>
       * The Subject's Type
       * </pre>
       *
       * <code>.axoom.subjects.v1.SubjectType subject_type = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          axoom.subjects.v1.Subjects.SubjectType, axoom.subjects.v1.Subjects.SubjectType.Builder, axoom.subjects.v1.Subjects.SubjectTypeOrBuilder> 
          getSubjectTypeFieldBuilder() {
        if (subjectTypeBuilder_ == null) {
          subjectTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              axoom.subjects.v1.Subjects.SubjectType, axoom.subjects.v1.Subjects.SubjectType.Builder, axoom.subjects.v1.Subjects.SubjectTypeOrBuilder>(
                  getSubjectType(),
                  getParentForChildren(),
                  isClean());
          subjectType_ = null;
        }
        return subjectTypeBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> labels_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetLabels() {
        if (labels_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              LabelsDefaultEntryHolder.defaultEntry);
        }
        return labels_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableLabels() {
        onChanged();;
        if (labels_ == null) {
          labels_ = com.google.protobuf.MapField.newMapField(
              LabelsDefaultEntryHolder.defaultEntry);
        }
        if (!labels_.isMutable()) {
          labels_ = labels_.copy();
        }
        return labels_;
      }

      public int getLabelsCount() {
        return internalGetLabels().getMap().size();
      }
      /**
       * <pre>
       * Additional free-form labels
       * </pre>
       *
       * <code>map&lt;string, string&gt; labels = 4;</code>
       */

      public boolean containsLabels(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetLabels().getMap().containsKey(key);
      }
      /**
       * Use {@link #getLabelsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getLabels() {
        return getLabelsMap();
      }
      /**
       * <pre>
       * Additional free-form labels
       * </pre>
       *
       * <code>map&lt;string, string&gt; labels = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getLabelsMap() {
        return internalGetLabels().getMap();
      }
      /**
       * <pre>
       * Additional free-form labels
       * </pre>
       *
       * <code>map&lt;string, string&gt; labels = 4;</code>
       */

      public java.lang.String getLabelsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetLabels().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Additional free-form labels
       * </pre>
       *
       * <code>map&lt;string, string&gt; labels = 4;</code>
       */

      public java.lang.String getLabelsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetLabels().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearLabels() {
        internalGetMutableLabels().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Additional free-form labels
       * </pre>
       *
       * <code>map&lt;string, string&gt; labels = 4;</code>
       */

      public Builder removeLabels(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableLabels().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableLabels() {
        return internalGetMutableLabels().getMutableMap();
      }
      /**
       * <pre>
       * Additional free-form labels
       * </pre>
       *
       * <code>map&lt;string, string&gt; labels = 4;</code>
       */
      public Builder putLabels(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableLabels().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Additional free-form labels
       * </pre>
       *
       * <code>map&lt;string, string&gt; labels = 4;</code>
       */

      public Builder putAllLabels(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableLabels().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:axoom.subjects.v1.Subject)
    }

    // @@protoc_insertion_point(class_scope:axoom.subjects.v1.Subject)
    private static final axoom.subjects.v1.Subjects.Subject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new axoom.subjects.v1.Subjects.Subject();
    }

    public static axoom.subjects.v1.Subjects.Subject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subject>
        PARSER = new com.google.protobuf.AbstractParser<Subject>() {
      public Subject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Subject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Subject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subject> getParserForType() {
      return PARSER;
    }

    public axoom.subjects.v1.Subjects.Subject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubjectTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axoom.subjects.v1.SubjectType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The unique SubjectType ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     * The unique SubjectType ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * The schema used in Records from Subjects of this SubjectType
     * </pre>
     *
     * <code>string record_schema_url = 2;</code>
     */
    java.lang.String getRecordSchemaUrl();
    /**
     * <pre>
     * The schema used in Records from Subjects of this SubjectType
     * </pre>
     *
     * <code>string record_schema_url = 2;</code>
     */
    com.google.protobuf.ByteString
        getRecordSchemaUrlBytes();

    /**
     * <pre>
     * The schema used in RecordMetas from Subjects of this SubjectType
     * </pre>
     *
     * <code>string record_meta_schema_url = 3;</code>
     */
    java.lang.String getRecordMetaSchemaUrl();
    /**
     * <pre>
     * The schema used in RecordMetas from Subjects of this SubjectType
     * </pre>
     *
     * <code>string record_meta_schema_url = 3;</code>
     */
    com.google.protobuf.ByteString
        getRecordMetaSchemaUrlBytes();
  }
  /**
   * Protobuf type {@code axoom.subjects.v1.SubjectType}
   */
  public  static final class SubjectType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:axoom.subjects.v1.SubjectType)
      SubjectTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubjectType.newBuilder() to construct.
    private SubjectType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubjectType() {
      id_ = "";
      recordSchemaUrl_ = "";
      recordMetaSchemaUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubjectType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              recordSchemaUrl_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              recordMetaSchemaUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_SubjectType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_SubjectType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              axoom.subjects.v1.Subjects.SubjectType.class, axoom.subjects.v1.Subjects.SubjectType.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * The unique SubjectType ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The unique SubjectType ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORD_SCHEMA_URL_FIELD_NUMBER = 2;
    private volatile java.lang.Object recordSchemaUrl_;
    /**
     * <pre>
     * The schema used in Records from Subjects of this SubjectType
     * </pre>
     *
     * <code>string record_schema_url = 2;</code>
     */
    public java.lang.String getRecordSchemaUrl() {
      java.lang.Object ref = recordSchemaUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordSchemaUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The schema used in Records from Subjects of this SubjectType
     * </pre>
     *
     * <code>string record_schema_url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRecordSchemaUrlBytes() {
      java.lang.Object ref = recordSchemaUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordSchemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORD_META_SCHEMA_URL_FIELD_NUMBER = 3;
    private volatile java.lang.Object recordMetaSchemaUrl_;
    /**
     * <pre>
     * The schema used in RecordMetas from Subjects of this SubjectType
     * </pre>
     *
     * <code>string record_meta_schema_url = 3;</code>
     */
    public java.lang.String getRecordMetaSchemaUrl() {
      java.lang.Object ref = recordMetaSchemaUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordMetaSchemaUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The schema used in RecordMetas from Subjects of this SubjectType
     * </pre>
     *
     * <code>string record_meta_schema_url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRecordMetaSchemaUrlBytes() {
      java.lang.Object ref = recordMetaSchemaUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordMetaSchemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getRecordSchemaUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, recordSchemaUrl_);
      }
      if (!getRecordMetaSchemaUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, recordMetaSchemaUrl_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getRecordSchemaUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, recordSchemaUrl_);
      }
      if (!getRecordMetaSchemaUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, recordMetaSchemaUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof axoom.subjects.v1.Subjects.SubjectType)) {
        return super.equals(obj);
      }
      axoom.subjects.v1.Subjects.SubjectType other = (axoom.subjects.v1.Subjects.SubjectType) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getRecordSchemaUrl()
          .equals(other.getRecordSchemaUrl());
      result = result && getRecordMetaSchemaUrl()
          .equals(other.getRecordMetaSchemaUrl());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + RECORD_SCHEMA_URL_FIELD_NUMBER;
      hash = (53 * hash) + getRecordSchemaUrl().hashCode();
      hash = (37 * hash) + RECORD_META_SCHEMA_URL_FIELD_NUMBER;
      hash = (53 * hash) + getRecordMetaSchemaUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.subjects.v1.Subjects.SubjectType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(axoom.subjects.v1.Subjects.SubjectType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code axoom.subjects.v1.SubjectType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:axoom.subjects.v1.SubjectType)
        axoom.subjects.v1.Subjects.SubjectTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_SubjectType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_SubjectType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                axoom.subjects.v1.Subjects.SubjectType.class, axoom.subjects.v1.Subjects.SubjectType.Builder.class);
      }

      // Construct using axoom.subjects.v1.Subjects.SubjectType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        recordSchemaUrl_ = "";

        recordMetaSchemaUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return axoom.subjects.v1.Subjects.internal_static_axoom_subjects_v1_SubjectType_descriptor;
      }

      public axoom.subjects.v1.Subjects.SubjectType getDefaultInstanceForType() {
        return axoom.subjects.v1.Subjects.SubjectType.getDefaultInstance();
      }

      public axoom.subjects.v1.Subjects.SubjectType build() {
        axoom.subjects.v1.Subjects.SubjectType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public axoom.subjects.v1.Subjects.SubjectType buildPartial() {
        axoom.subjects.v1.Subjects.SubjectType result = new axoom.subjects.v1.Subjects.SubjectType(this);
        result.id_ = id_;
        result.recordSchemaUrl_ = recordSchemaUrl_;
        result.recordMetaSchemaUrl_ = recordMetaSchemaUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof axoom.subjects.v1.Subjects.SubjectType) {
          return mergeFrom((axoom.subjects.v1.Subjects.SubjectType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(axoom.subjects.v1.Subjects.SubjectType other) {
        if (other == axoom.subjects.v1.Subjects.SubjectType.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getRecordSchemaUrl().isEmpty()) {
          recordSchemaUrl_ = other.recordSchemaUrl_;
          onChanged();
        }
        if (!other.getRecordMetaSchemaUrl().isEmpty()) {
          recordMetaSchemaUrl_ = other.recordMetaSchemaUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        axoom.subjects.v1.Subjects.SubjectType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (axoom.subjects.v1.Subjects.SubjectType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * The unique SubjectType ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The unique SubjectType ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The unique SubjectType ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique SubjectType ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique SubjectType ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recordSchemaUrl_ = "";
      /**
       * <pre>
       * The schema used in Records from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_schema_url = 2;</code>
       */
      public java.lang.String getRecordSchemaUrl() {
        java.lang.Object ref = recordSchemaUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordSchemaUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The schema used in Records from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_schema_url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRecordSchemaUrlBytes() {
        java.lang.Object ref = recordSchemaUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordSchemaUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The schema used in Records from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_schema_url = 2;</code>
       */
      public Builder setRecordSchemaUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordSchemaUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The schema used in Records from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_schema_url = 2;</code>
       */
      public Builder clearRecordSchemaUrl() {
        
        recordSchemaUrl_ = getDefaultInstance().getRecordSchemaUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The schema used in Records from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_schema_url = 2;</code>
       */
      public Builder setRecordSchemaUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordSchemaUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recordMetaSchemaUrl_ = "";
      /**
       * <pre>
       * The schema used in RecordMetas from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_meta_schema_url = 3;</code>
       */
      public java.lang.String getRecordMetaSchemaUrl() {
        java.lang.Object ref = recordMetaSchemaUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordMetaSchemaUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The schema used in RecordMetas from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_meta_schema_url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRecordMetaSchemaUrlBytes() {
        java.lang.Object ref = recordMetaSchemaUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordMetaSchemaUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The schema used in RecordMetas from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_meta_schema_url = 3;</code>
       */
      public Builder setRecordMetaSchemaUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordMetaSchemaUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The schema used in RecordMetas from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_meta_schema_url = 3;</code>
       */
      public Builder clearRecordMetaSchemaUrl() {
        
        recordMetaSchemaUrl_ = getDefaultInstance().getRecordMetaSchemaUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The schema used in RecordMetas from Subjects of this SubjectType
       * </pre>
       *
       * <code>string record_meta_schema_url = 3;</code>
       */
      public Builder setRecordMetaSchemaUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordMetaSchemaUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:axoom.subjects.v1.SubjectType)
    }

    // @@protoc_insertion_point(class_scope:axoom.subjects.v1.SubjectType)
    private static final axoom.subjects.v1.Subjects.SubjectType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new axoom.subjects.v1.Subjects.SubjectType();
    }

    public static axoom.subjects.v1.Subjects.SubjectType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubjectType>
        PARSER = new com.google.protobuf.AbstractParser<SubjectType>() {
      public SubjectType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubjectType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubjectType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubjectType> getParserForType() {
      return PARSER;
    }

    public axoom.subjects.v1.Subjects.SubjectType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_subjects_v1_Subject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_subjects_v1_Subject_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_subjects_v1_Subject_LabelsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_subjects_v1_Subject_LabelsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_subjects_v1_SubjectType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_subjects_v1_SubjectType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016subjects.proto\022\021axoom.subjects.v1\"\300\001\n\007" +
      "Subject\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\0224\n\014sub" +
      "ject_type\030\003 \001(\0132\036.axoom.subjects.v1.Subj" +
      "ectType\0226\n\006labels\030\004 \003(\0132&.axoom.subjects" +
      ".v1.Subject.LabelsEntry\032-\n\013LabelsEntry\022\013" +
      "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"T\n\013Subjec" +
      "tType\022\n\n\002id\030\001 \001(\t\022\031\n\021record_schema_url\030\002" +
      " \001(\t\022\036\n\026record_meta_schema_url\030\003 \001(\tB-Z+" +
      "gitlab.axoom.tech/iot/go-rillaz/subjects" +
      "/v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_axoom_subjects_v1_Subject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_axoom_subjects_v1_Subject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_subjects_v1_Subject_descriptor,
        new java.lang.String[] { "Id", "Name", "SubjectType", "Labels", });
    internal_static_axoom_subjects_v1_Subject_LabelsEntry_descriptor =
      internal_static_axoom_subjects_v1_Subject_descriptor.getNestedTypes().get(0);
    internal_static_axoom_subjects_v1_Subject_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_subjects_v1_Subject_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_axoom_subjects_v1_SubjectType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_axoom_subjects_v1_SubjectType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_subjects_v1_SubjectType_descriptor,
        new java.lang.String[] { "Id", "RecordSchemaUrl", "RecordMetaSchemaUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
