image: axoom-docker.jfrog.io/axoom/iot/maven-chromedriver:0.1.0-alpha0001

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:dev:
  stage: test
#  artifacts:
#    reports:
#      junit:
#        - target/surefire-reports/TEST-*.xml
#        - target/failsafe-reports/TEST-*.xml
  script:
    - export IOT_PROVIDER=google
    - export MACHINE_TYPE=humidity
    - export MACHINE_IDS=machine_1,machine_2
    - export DEVICE_NAME=shashi
    - export LOG_LEVEL=DEBUG
    - export TENANT_ID=integrationtest
    - export PROVIDER_REGION=europe-west1
    - export CIS_URL=https://account.dev.myaxoom.com
    - export DRS_URL=https://device-registration-service.dev.myaxoom.com
    - export DRS_CLIENT_ID=$DEV_DRS_CLIENT_ID
    - export SECRET=$DEV_SECRET
    - export DRS_SCOPES="device-registration-service.devices.write device-registration-service.devices.read"
    - export SYSTEM_INTEGRATOR_EMAIL=264d0dac.axoom.com@emea.teams.ms
    - export SYSTEM_INTEGRATOR_PASSWORD=kafkarulestheaxoom2world
    - export DRS_DEVICES_API=/api/v1/devices
    - export DRS_REDIRECT_URI=https://device-registration-service.dev.myaxoom.com/swagger/oauth2-redirect.html
    - export SRS_API=/api/v1/schemas
    - export MVP-KAFKA=mvp-kafka:9092
    - export PROJECT_ID=mvp-iotcore-eval
    - export SRS_CLIENT_ID=mvp-schema-registration-service-swagger
    - export SRS_REDIRECT_URI=https://schema-registration-service.dev.myaxoom.com/swagger/oauth2-redirect.html
    - export SRS_SCOPES="schema-registration-service.schemas.write schema-registration-service.schemas.read"
    - export SRS_URL=https://schema-registration-service.dev.myaxoom.com
    - export DCS_API=/api/v1/datacompositions
    - export DCS_CLIENT_ID=mvp-data-composition-service-swagger
    - export DCS_REDIRECT_URI=https://data-composition-service.dev.myaxoom.com/swagger/oauth2-redirect.html
    - export DCS_SCOPES="data-composition-service.data-composition.read data-composition-service.data-composition.write"
    - export DCS_URL=https://data-composition-service.dev.myaxoom.com
    - mvn $MAVEN_CLI_OPTS verify package
