// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mappingz.proto

package axoom.mappingz.v1;

public final class Mappingz {
  private Mappingz() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MappingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axoom.mappingz.v1.Mapping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The unique identitfier for the preprocessing
     * </pre>
     *
     * <code>string preprocessing_id = 1;</code>
     */
    java.lang.String getPreprocessingId();
    /**
     * <pre>
     * The unique identitfier for the preprocessing
     * </pre>
     *
     * <code>string preprocessing_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPreprocessingIdBytes();

    /**
     * <pre>
     * The unique identifier of the subject, this mapping belongs to
     * </pre>
     *
     * <code>string subject_id = 2;</code>
     */
    java.lang.String getSubjectId();
    /**
     * <pre>
     * The unique identifier of the subject, this mapping belongs to
     * </pre>
     *
     * <code>string subject_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubjectIdBytes();

    /**
     * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
     */
    boolean hasExpression();
    /**
     * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
     */
    axoom.mappingz.v1.Mappingz.Expression getExpression();
    /**
     * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
     */
    axoom.mappingz.v1.Mappingz.ExpressionOrBuilder getExpressionOrBuilder();
  }
  /**
   * Protobuf type {@code axoom.mappingz.v1.Mapping}
   */
  public  static final class Mapping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:axoom.mappingz.v1.Mapping)
      MappingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Mapping.newBuilder() to construct.
    private Mapping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Mapping() {
      preprocessingId_ = "";
      subjectId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Mapping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              preprocessingId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              subjectId_ = s;
              break;
            }
            case 26: {
              axoom.mappingz.v1.Mappingz.Expression.Builder subBuilder = null;
              if (expression_ != null) {
                subBuilder = expression_.toBuilder();
              }
              expression_ = input.readMessage(axoom.mappingz.v1.Mappingz.Expression.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(expression_);
                expression_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Mapping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Mapping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              axoom.mappingz.v1.Mappingz.Mapping.class, axoom.mappingz.v1.Mappingz.Mapping.Builder.class);
    }

    public static final int PREPROCESSING_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object preprocessingId_;
    /**
     * <pre>
     * The unique identitfier for the preprocessing
     * </pre>
     *
     * <code>string preprocessing_id = 1;</code>
     */
    public java.lang.String getPreprocessingId() {
      java.lang.Object ref = preprocessingId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        preprocessingId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The unique identitfier for the preprocessing
     * </pre>
     *
     * <code>string preprocessing_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPreprocessingIdBytes() {
      java.lang.Object ref = preprocessingId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preprocessingId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object subjectId_;
    /**
     * <pre>
     * The unique identifier of the subject, this mapping belongs to
     * </pre>
     *
     * <code>string subject_id = 2;</code>
     */
    public java.lang.String getSubjectId() {
      java.lang.Object ref = subjectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The unique identifier of the subject, this mapping belongs to
     * </pre>
     *
     * <code>string subject_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectIdBytes() {
      java.lang.Object ref = subjectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPRESSION_FIELD_NUMBER = 3;
    private axoom.mappingz.v1.Mappingz.Expression expression_;
    /**
     * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
     */
    public boolean hasExpression() {
      return expression_ != null;
    }
    /**
     * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
     */
    public axoom.mappingz.v1.Mappingz.Expression getExpression() {
      return expression_ == null ? axoom.mappingz.v1.Mappingz.Expression.getDefaultInstance() : expression_;
    }
    /**
     * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
     */
    public axoom.mappingz.v1.Mappingz.ExpressionOrBuilder getExpressionOrBuilder() {
      return getExpression();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPreprocessingIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, preprocessingId_);
      }
      if (!getSubjectIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subjectId_);
      }
      if (expression_ != null) {
        output.writeMessage(3, getExpression());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPreprocessingIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, preprocessingId_);
      }
      if (!getSubjectIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subjectId_);
      }
      if (expression_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getExpression());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof axoom.mappingz.v1.Mappingz.Mapping)) {
        return super.equals(obj);
      }
      axoom.mappingz.v1.Mappingz.Mapping other = (axoom.mappingz.v1.Mappingz.Mapping) obj;

      boolean result = true;
      result = result && getPreprocessingId()
          .equals(other.getPreprocessingId());
      result = result && getSubjectId()
          .equals(other.getSubjectId());
      result = result && (hasExpression() == other.hasExpression());
      if (hasExpression()) {
        result = result && getExpression()
            .equals(other.getExpression());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PREPROCESSING_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPreprocessingId().hashCode();
      hash = (37 * hash) + SUBJECT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSubjectId().hashCode();
      if (hasExpression()) {
        hash = (37 * hash) + EXPRESSION_FIELD_NUMBER;
        hash = (53 * hash) + getExpression().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.mappingz.v1.Mappingz.Mapping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(axoom.mappingz.v1.Mappingz.Mapping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code axoom.mappingz.v1.Mapping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:axoom.mappingz.v1.Mapping)
        axoom.mappingz.v1.Mappingz.MappingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Mapping_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Mapping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                axoom.mappingz.v1.Mappingz.Mapping.class, axoom.mappingz.v1.Mappingz.Mapping.Builder.class);
      }

      // Construct using axoom.mappingz.v1.Mappingz.Mapping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        preprocessingId_ = "";

        subjectId_ = "";

        if (expressionBuilder_ == null) {
          expression_ = null;
        } else {
          expression_ = null;
          expressionBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Mapping_descriptor;
      }

      @java.lang.Override
      public axoom.mappingz.v1.Mappingz.Mapping getDefaultInstanceForType() {
        return axoom.mappingz.v1.Mappingz.Mapping.getDefaultInstance();
      }

      @java.lang.Override
      public axoom.mappingz.v1.Mappingz.Mapping build() {
        axoom.mappingz.v1.Mappingz.Mapping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public axoom.mappingz.v1.Mappingz.Mapping buildPartial() {
        axoom.mappingz.v1.Mappingz.Mapping result = new axoom.mappingz.v1.Mappingz.Mapping(this);
        result.preprocessingId_ = preprocessingId_;
        result.subjectId_ = subjectId_;
        if (expressionBuilder_ == null) {
          result.expression_ = expression_;
        } else {
          result.expression_ = expressionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof axoom.mappingz.v1.Mappingz.Mapping) {
          return mergeFrom((axoom.mappingz.v1.Mappingz.Mapping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(axoom.mappingz.v1.Mappingz.Mapping other) {
        if (other == axoom.mappingz.v1.Mappingz.Mapping.getDefaultInstance()) return this;
        if (!other.getPreprocessingId().isEmpty()) {
          preprocessingId_ = other.preprocessingId_;
          onChanged();
        }
        if (!other.getSubjectId().isEmpty()) {
          subjectId_ = other.subjectId_;
          onChanged();
        }
        if (other.hasExpression()) {
          mergeExpression(other.getExpression());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        axoom.mappingz.v1.Mappingz.Mapping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (axoom.mappingz.v1.Mappingz.Mapping) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object preprocessingId_ = "";
      /**
       * <pre>
       * The unique identitfier for the preprocessing
       * </pre>
       *
       * <code>string preprocessing_id = 1;</code>
       */
      public java.lang.String getPreprocessingId() {
        java.lang.Object ref = preprocessingId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          preprocessingId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The unique identitfier for the preprocessing
       * </pre>
       *
       * <code>string preprocessing_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPreprocessingIdBytes() {
        java.lang.Object ref = preprocessingId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          preprocessingId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The unique identitfier for the preprocessing
       * </pre>
       *
       * <code>string preprocessing_id = 1;</code>
       */
      public Builder setPreprocessingId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        preprocessingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique identitfier for the preprocessing
       * </pre>
       *
       * <code>string preprocessing_id = 1;</code>
       */
      public Builder clearPreprocessingId() {
        
        preprocessingId_ = getDefaultInstance().getPreprocessingId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique identitfier for the preprocessing
       * </pre>
       *
       * <code>string preprocessing_id = 1;</code>
       */
      public Builder setPreprocessingIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        preprocessingId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subjectId_ = "";
      /**
       * <pre>
       * The unique identifier of the subject, this mapping belongs to
       * </pre>
       *
       * <code>string subject_id = 2;</code>
       */
      public java.lang.String getSubjectId() {
        java.lang.Object ref = subjectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subjectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The unique identifier of the subject, this mapping belongs to
       * </pre>
       *
       * <code>string subject_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectIdBytes() {
        java.lang.Object ref = subjectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subjectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The unique identifier of the subject, this mapping belongs to
       * </pre>
       *
       * <code>string subject_id = 2;</code>
       */
      public Builder setSubjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subjectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique identifier of the subject, this mapping belongs to
       * </pre>
       *
       * <code>string subject_id = 2;</code>
       */
      public Builder clearSubjectId() {
        
        subjectId_ = getDefaultInstance().getSubjectId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique identifier of the subject, this mapping belongs to
       * </pre>
       *
       * <code>string subject_id = 2;</code>
       */
      public Builder setSubjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subjectId_ = value;
        onChanged();
        return this;
      }

      private axoom.mappingz.v1.Mappingz.Expression expression_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          axoom.mappingz.v1.Mappingz.Expression, axoom.mappingz.v1.Mappingz.Expression.Builder, axoom.mappingz.v1.Mappingz.ExpressionOrBuilder> expressionBuilder_;
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      public boolean hasExpression() {
        return expressionBuilder_ != null || expression_ != null;
      }
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      public axoom.mappingz.v1.Mappingz.Expression getExpression() {
        if (expressionBuilder_ == null) {
          return expression_ == null ? axoom.mappingz.v1.Mappingz.Expression.getDefaultInstance() : expression_;
        } else {
          return expressionBuilder_.getMessage();
        }
      }
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      public Builder setExpression(axoom.mappingz.v1.Mappingz.Expression value) {
        if (expressionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          expression_ = value;
          onChanged();
        } else {
          expressionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      public Builder setExpression(
          axoom.mappingz.v1.Mappingz.Expression.Builder builderForValue) {
        if (expressionBuilder_ == null) {
          expression_ = builderForValue.build();
          onChanged();
        } else {
          expressionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      public Builder mergeExpression(axoom.mappingz.v1.Mappingz.Expression value) {
        if (expressionBuilder_ == null) {
          if (expression_ != null) {
            expression_ =
              axoom.mappingz.v1.Mappingz.Expression.newBuilder(expression_).mergeFrom(value).buildPartial();
          } else {
            expression_ = value;
          }
          onChanged();
        } else {
          expressionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      public Builder clearExpression() {
        if (expressionBuilder_ == null) {
          expression_ = null;
          onChanged();
        } else {
          expression_ = null;
          expressionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      public axoom.mappingz.v1.Mappingz.Expression.Builder getExpressionBuilder() {
        
        onChanged();
        return getExpressionFieldBuilder().getBuilder();
      }
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      public axoom.mappingz.v1.Mappingz.ExpressionOrBuilder getExpressionOrBuilder() {
        if (expressionBuilder_ != null) {
          return expressionBuilder_.getMessageOrBuilder();
        } else {
          return expression_ == null ?
              axoom.mappingz.v1.Mappingz.Expression.getDefaultInstance() : expression_;
        }
      }
      /**
       * <code>.axoom.mappingz.v1.Expression expression = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          axoom.mappingz.v1.Mappingz.Expression, axoom.mappingz.v1.Mappingz.Expression.Builder, axoom.mappingz.v1.Mappingz.ExpressionOrBuilder> 
          getExpressionFieldBuilder() {
        if (expressionBuilder_ == null) {
          expressionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              axoom.mappingz.v1.Mappingz.Expression, axoom.mappingz.v1.Mappingz.Expression.Builder, axoom.mappingz.v1.Mappingz.ExpressionOrBuilder>(
                  getExpression(),
                  getParentForChildren(),
                  isClean());
          expression_ = null;
        }
        return expressionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:axoom.mappingz.v1.Mapping)
    }

    // @@protoc_insertion_point(class_scope:axoom.mappingz.v1.Mapping)
    private static final axoom.mappingz.v1.Mappingz.Mapping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new axoom.mappingz.v1.Mappingz.Mapping();
    }

    public static axoom.mappingz.v1.Mappingz.Mapping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mapping>
        PARSER = new com.google.protobuf.AbstractParser<Mapping>() {
      @java.lang.Override
      public Mapping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mapping(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Mapping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mapping> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public axoom.mappingz.v1.Mappingz.Mapping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExpressionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axoom.mappingz.v1.Expression)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The actual expression presented as a string
     * </pre>
     *
     * <code>string expression_string = 1;</code>
     */
    java.lang.String getExpressionString();
    /**
     * <pre>
     * The actual expression presented as a string
     * </pre>
     *
     * <code>string expression_string = 1;</code>
     */
    com.google.protobuf.ByteString
        getExpressionStringBytes();

    /**
     * <pre>
     * The Expression's type
     * </pre>
     *
     * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * The Expression's type
     * </pre>
     *
     * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
     */
    axoom.mappingz.v1.Mappingz.Expression.Type getType();
  }
  /**
   * Protobuf type {@code axoom.mappingz.v1.Expression}
   */
  public  static final class Expression extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:axoom.mappingz.v1.Expression)
      ExpressionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Expression.newBuilder() to construct.
    private Expression(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Expression() {
      expressionString_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Expression(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              expressionString_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Expression_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Expression_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              axoom.mappingz.v1.Mappingz.Expression.class, axoom.mappingz.v1.Mappingz.Expression.Builder.class);
    }

    /**
     * Protobuf enum {@code axoom.mappingz.v1.Expression.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <pre>
       * A declarative open-source query and transformation language for JSON data.
       * </pre>
       *
       * <code>JSONATA = 1;</code>
       */
      JSONATA(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <pre>
       * A declarative open-source query and transformation language for JSON data.
       * </pre>
       *
       * <code>JSONATA = 1;</code>
       */
      public static final int JSONATA_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return JSONATA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return axoom.mappingz.v1.Mappingz.Expression.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:axoom.mappingz.v1.Expression.Type)
    }

    public static final int EXPRESSION_STRING_FIELD_NUMBER = 1;
    private volatile java.lang.Object expressionString_;
    /**
     * <pre>
     * The actual expression presented as a string
     * </pre>
     *
     * <code>string expression_string = 1;</code>
     */
    public java.lang.String getExpressionString() {
      java.lang.Object ref = expressionString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expressionString_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The actual expression presented as a string
     * </pre>
     *
     * <code>string expression_string = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExpressionStringBytes() {
      java.lang.Object ref = expressionString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expressionString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     * The Expression's type
     * </pre>
     *
     * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * The Expression's type
     * </pre>
     *
     * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
     */
    public axoom.mappingz.v1.Mappingz.Expression.Type getType() {
      @SuppressWarnings("deprecation")
      axoom.mappingz.v1.Mappingz.Expression.Type result = axoom.mappingz.v1.Mappingz.Expression.Type.valueOf(type_);
      return result == null ? axoom.mappingz.v1.Mappingz.Expression.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getExpressionStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, expressionString_);
      }
      if (type_ != axoom.mappingz.v1.Mappingz.Expression.Type.UNKNOWN.getNumber()) {
        output.writeEnum(2, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getExpressionStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, expressionString_);
      }
      if (type_ != axoom.mappingz.v1.Mappingz.Expression.Type.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof axoom.mappingz.v1.Mappingz.Expression)) {
        return super.equals(obj);
      }
      axoom.mappingz.v1.Mappingz.Expression other = (axoom.mappingz.v1.Mappingz.Expression) obj;

      boolean result = true;
      result = result && getExpressionString()
          .equals(other.getExpressionString());
      result = result && type_ == other.type_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXPRESSION_STRING_FIELD_NUMBER;
      hash = (53 * hash) + getExpressionString().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.mappingz.v1.Mappingz.Expression parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(axoom.mappingz.v1.Mappingz.Expression prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code axoom.mappingz.v1.Expression}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:axoom.mappingz.v1.Expression)
        axoom.mappingz.v1.Mappingz.ExpressionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Expression_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Expression_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                axoom.mappingz.v1.Mappingz.Expression.class, axoom.mappingz.v1.Mappingz.Expression.Builder.class);
      }

      // Construct using axoom.mappingz.v1.Mappingz.Expression.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        expressionString_ = "";

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return axoom.mappingz.v1.Mappingz.internal_static_axoom_mappingz_v1_Expression_descriptor;
      }

      @java.lang.Override
      public axoom.mappingz.v1.Mappingz.Expression getDefaultInstanceForType() {
        return axoom.mappingz.v1.Mappingz.Expression.getDefaultInstance();
      }

      @java.lang.Override
      public axoom.mappingz.v1.Mappingz.Expression build() {
        axoom.mappingz.v1.Mappingz.Expression result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public axoom.mappingz.v1.Mappingz.Expression buildPartial() {
        axoom.mappingz.v1.Mappingz.Expression result = new axoom.mappingz.v1.Mappingz.Expression(this);
        result.expressionString_ = expressionString_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof axoom.mappingz.v1.Mappingz.Expression) {
          return mergeFrom((axoom.mappingz.v1.Mappingz.Expression)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(axoom.mappingz.v1.Mappingz.Expression other) {
        if (other == axoom.mappingz.v1.Mappingz.Expression.getDefaultInstance()) return this;
        if (!other.getExpressionString().isEmpty()) {
          expressionString_ = other.expressionString_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        axoom.mappingz.v1.Mappingz.Expression parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (axoom.mappingz.v1.Mappingz.Expression) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object expressionString_ = "";
      /**
       * <pre>
       * The actual expression presented as a string
       * </pre>
       *
       * <code>string expression_string = 1;</code>
       */
      public java.lang.String getExpressionString() {
        java.lang.Object ref = expressionString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expressionString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The actual expression presented as a string
       * </pre>
       *
       * <code>string expression_string = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExpressionStringBytes() {
        java.lang.Object ref = expressionString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expressionString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The actual expression presented as a string
       * </pre>
       *
       * <code>string expression_string = 1;</code>
       */
      public Builder setExpressionString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        expressionString_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual expression presented as a string
       * </pre>
       *
       * <code>string expression_string = 1;</code>
       */
      public Builder clearExpressionString() {
        
        expressionString_ = getDefaultInstance().getExpressionString();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual expression presented as a string
       * </pre>
       *
       * <code>string expression_string = 1;</code>
       */
      public Builder setExpressionStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        expressionString_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * The Expression's type
       * </pre>
       *
       * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * The Expression's type
       * </pre>
       *
       * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Expression's type
       * </pre>
       *
       * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
       */
      public axoom.mappingz.v1.Mappingz.Expression.Type getType() {
        @SuppressWarnings("deprecation")
        axoom.mappingz.v1.Mappingz.Expression.Type result = axoom.mappingz.v1.Mappingz.Expression.Type.valueOf(type_);
        return result == null ? axoom.mappingz.v1.Mappingz.Expression.Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The Expression's type
       * </pre>
       *
       * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
       */
      public Builder setType(axoom.mappingz.v1.Mappingz.Expression.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Expression's type
       * </pre>
       *
       * <code>.axoom.mappingz.v1.Expression.Type type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:axoom.mappingz.v1.Expression)
    }

    // @@protoc_insertion_point(class_scope:axoom.mappingz.v1.Expression)
    private static final axoom.mappingz.v1.Mappingz.Expression DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new axoom.mappingz.v1.Mappingz.Expression();
    }

    public static axoom.mappingz.v1.Mappingz.Expression getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Expression>
        PARSER = new com.google.protobuf.AbstractParser<Expression>() {
      @java.lang.Override
      public Expression parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Expression(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Expression> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Expression> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public axoom.mappingz.v1.Mappingz.Expression getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_mappingz_v1_Mapping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_mappingz_v1_Mapping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_mappingz_v1_Expression_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_mappingz_v1_Expression_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016mappingz.proto\022\021axoom.mappingz.v1\"j\n\007M" +
      "apping\022\030\n\020preprocessing_id\030\001 \001(\t\022\022\n\nsubj" +
      "ect_id\030\002 \001(\t\0221\n\nexpression\030\003 \001(\0132\035.axoom" +
      ".mappingz.v1.Expression\"{\n\nExpression\022\031\n" +
      "\021expression_string\030\001 \001(\t\0220\n\004type\030\002 \001(\0162\"" +
      ".axoom.mappingz.v1.Expression.Type\" \n\004Ty" +
      "pe\022\013\n\007UNKNOWN\020\000\022\013\n\007JSONATA\020\001B-Z+gitlab.a" +
      "xoom.tech/iot/go-rillaz/mappingz/v1b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_axoom_mappingz_v1_Mapping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_axoom_mappingz_v1_Mapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_mappingz_v1_Mapping_descriptor,
        new java.lang.String[] { "PreprocessingId", "SubjectId", "Expression", });
    internal_static_axoom_mappingz_v1_Expression_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_axoom_mappingz_v1_Expression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_mappingz_v1_Expression_descriptor,
        new java.lang.String[] { "ExpressionString", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
