// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recordmetas.proto

package axoom.recordmetas.v1;

public final class Recordmetas {
  private Recordmetas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axoom.recordmetas.v1.RecordMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
     */
    boolean hasHeaders();
    /**
     * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
     */
    axoom.recordmetas.v1.Recordmetas.RecordMetaHeader getHeaders();
    /**
     * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
     */
    axoom.recordmetas.v1.Recordmetas.RecordMetaHeaderOrBuilder getHeadersOrBuilder();

    /**
     * <code>bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code axoom.recordmetas.v1.RecordMeta}
   */
  public  static final class RecordMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:axoom.recordmetas.v1.RecordMeta)
      RecordMetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecordMeta.newBuilder() to construct.
    private RecordMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordMeta() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecordMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.Builder subBuilder = null;
              if (headers_ != null) {
                subBuilder = headers_.toBuilder();
              }
              headers_ = input.readMessage(axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(headers_);
                headers_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              axoom.recordmetas.v1.Recordmetas.RecordMeta.class, axoom.recordmetas.v1.Recordmetas.RecordMeta.Builder.class);
    }

    public static final int HEADERS_FIELD_NUMBER = 1;
    private axoom.recordmetas.v1.Recordmetas.RecordMetaHeader headers_;
    /**
     * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
     */
    public boolean hasHeaders() {
      return headers_ != null;
    }
    /**
     * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
     */
    public axoom.recordmetas.v1.Recordmetas.RecordMetaHeader getHeaders() {
      return headers_ == null ? axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.getDefaultInstance() : headers_;
    }
    /**
     * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
     */
    public axoom.recordmetas.v1.Recordmetas.RecordMetaHeaderOrBuilder getHeadersOrBuilder() {
      return getHeaders();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (headers_ != null) {
        output.writeMessage(1, getHeaders());
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (headers_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeaders());
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof axoom.recordmetas.v1.Recordmetas.RecordMeta)) {
        return super.equals(obj);
      }
      axoom.recordmetas.v1.Recordmetas.RecordMeta other = (axoom.recordmetas.v1.Recordmetas.RecordMeta) obj;

      boolean result = true;
      result = result && (hasHeaders() == other.hasHeaders());
      if (hasHeaders()) {
        result = result && getHeaders()
            .equals(other.getHeaders());
      }
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeaders()) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + getHeaders().hashCode();
      }
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(axoom.recordmetas.v1.Recordmetas.RecordMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code axoom.recordmetas.v1.RecordMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:axoom.recordmetas.v1.RecordMeta)
        axoom.recordmetas.v1.Recordmetas.RecordMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                axoom.recordmetas.v1.Recordmetas.RecordMeta.class, axoom.recordmetas.v1.Recordmetas.RecordMeta.Builder.class);
      }

      // Construct using axoom.recordmetas.v1.Recordmetas.RecordMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headersBuilder_ == null) {
          headers_ = null;
        } else {
          headers_ = null;
          headersBuilder_ = null;
        }
        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMeta_descriptor;
      }

      public axoom.recordmetas.v1.Recordmetas.RecordMeta getDefaultInstanceForType() {
        return axoom.recordmetas.v1.Recordmetas.RecordMeta.getDefaultInstance();
      }

      public axoom.recordmetas.v1.Recordmetas.RecordMeta build() {
        axoom.recordmetas.v1.Recordmetas.RecordMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public axoom.recordmetas.v1.Recordmetas.RecordMeta buildPartial() {
        axoom.recordmetas.v1.Recordmetas.RecordMeta result = new axoom.recordmetas.v1.Recordmetas.RecordMeta(this);
        if (headersBuilder_ == null) {
          result.headers_ = headers_;
        } else {
          result.headers_ = headersBuilder_.build();
        }
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof axoom.recordmetas.v1.Recordmetas.RecordMeta) {
          return mergeFrom((axoom.recordmetas.v1.Recordmetas.RecordMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(axoom.recordmetas.v1.Recordmetas.RecordMeta other) {
        if (other == axoom.recordmetas.v1.Recordmetas.RecordMeta.getDefaultInstance()) return this;
        if (other.hasHeaders()) {
          mergeHeaders(other.getHeaders());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        axoom.recordmetas.v1.Recordmetas.RecordMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (axoom.recordmetas.v1.Recordmetas.RecordMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private axoom.recordmetas.v1.Recordmetas.RecordMetaHeader headers_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          axoom.recordmetas.v1.Recordmetas.RecordMetaHeader, axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.Builder, axoom.recordmetas.v1.Recordmetas.RecordMetaHeaderOrBuilder> headersBuilder_;
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      public boolean hasHeaders() {
        return headersBuilder_ != null || headers_ != null;
      }
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      public axoom.recordmetas.v1.Recordmetas.RecordMetaHeader getHeaders() {
        if (headersBuilder_ == null) {
          return headers_ == null ? axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.getDefaultInstance() : headers_;
        } else {
          return headersBuilder_.getMessage();
        }
      }
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      public Builder setHeaders(axoom.recordmetas.v1.Recordmetas.RecordMetaHeader value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          headers_ = value;
          onChanged();
        } else {
          headersBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      public Builder setHeaders(
          axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.Builder builderForValue) {
        if (headersBuilder_ == null) {
          headers_ = builderForValue.build();
          onChanged();
        } else {
          headersBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      public Builder mergeHeaders(axoom.recordmetas.v1.Recordmetas.RecordMetaHeader value) {
        if (headersBuilder_ == null) {
          if (headers_ != null) {
            headers_ =
              axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.newBuilder(headers_).mergeFrom(value).buildPartial();
          } else {
            headers_ = value;
          }
          onChanged();
        } else {
          headersBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      public Builder clearHeaders() {
        if (headersBuilder_ == null) {
          headers_ = null;
          onChanged();
        } else {
          headers_ = null;
          headersBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      public axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.Builder getHeadersBuilder() {
        
        onChanged();
        return getHeadersFieldBuilder().getBuilder();
      }
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      public axoom.recordmetas.v1.Recordmetas.RecordMetaHeaderOrBuilder getHeadersOrBuilder() {
        if (headersBuilder_ != null) {
          return headersBuilder_.getMessageOrBuilder();
        } else {
          return headers_ == null ?
              axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.getDefaultInstance() : headers_;
        }
      }
      /**
       * <code>.axoom.recordmetas.v1.RecordMetaHeader headers = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          axoom.recordmetas.v1.Recordmetas.RecordMetaHeader, axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.Builder, axoom.recordmetas.v1.Recordmetas.RecordMetaHeaderOrBuilder> 
          getHeadersFieldBuilder() {
        if (headersBuilder_ == null) {
          headersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              axoom.recordmetas.v1.Recordmetas.RecordMetaHeader, axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.Builder, axoom.recordmetas.v1.Recordmetas.RecordMetaHeaderOrBuilder>(
                  getHeaders(),
                  getParentForChildren(),
                  isClean());
          headers_ = null;
        }
        return headersBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:axoom.recordmetas.v1.RecordMeta)
    }

    // @@protoc_insertion_point(class_scope:axoom.recordmetas.v1.RecordMeta)
    private static final axoom.recordmetas.v1.Recordmetas.RecordMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new axoom.recordmetas.v1.Recordmetas.RecordMeta();
    }

    public static axoom.recordmetas.v1.Recordmetas.RecordMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecordMeta>
        PARSER = new com.google.protobuf.AbstractParser<RecordMeta>() {
      public RecordMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecordMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecordMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordMeta> getParserForType() {
      return PARSER;
    }

    public axoom.recordmetas.v1.Recordmetas.RecordMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RecordMetaHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axoom.recordmetas.v1.RecordMetaHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The unique record meta ID
     * </pre>
     *
     * <code>string record_meta_id = 2;</code>
     */
    java.lang.String getRecordMetaId();
    /**
     * <pre>
     * The unique record meta ID
     * </pre>
     *
     * <code>string record_meta_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getRecordMetaIdBytes();

    /**
     * <pre>
     * The unique subject ID
     * </pre>
     *
     * <code>string subject_id = 3;</code>
     */
    java.lang.String getSubjectId();
    /**
     * <pre>
     * The unique subject ID
     * </pre>
     *
     * <code>string subject_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubjectIdBytes();

    /**
     * <pre>
     * The unique subject type ID
     * </pre>
     *
     * <code>string subject_type = 4;</code>
     */
    java.lang.String getSubjectType();
    /**
     * <pre>
     * The unique subject type ID
     * </pre>
     *
     * <code>string subject_type = 4;</code>
     */
    com.google.protobuf.ByteString
        getSubjectTypeBytes();

    /**
     * <pre>
     * The url where the schema is located
     * </pre>
     *
     * <code>string schema_url = 5;</code>
     */
    java.lang.String getSchemaUrl();
    /**
     * <pre>
     * The url where the schema is located
     * </pre>
     *
     * <code>string schema_url = 5;</code>
     */
    com.google.protobuf.ByteString
        getSchemaUrlBytes();

    /**
     * <pre>
     * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
     * </pre>
     *
     * <code>string timestamp = 6;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
     * </pre>
     *
     * <code>string timestamp = 6;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();
  }
  /**
   * Protobuf type {@code axoom.recordmetas.v1.RecordMetaHeader}
   */
  public  static final class RecordMetaHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:axoom.recordmetas.v1.RecordMetaHeader)
      RecordMetaHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecordMetaHeader.newBuilder() to construct.
    private RecordMetaHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordMetaHeader() {
      recordMetaId_ = "";
      subjectId_ = "";
      subjectType_ = "";
      schemaUrl_ = "";
      timestamp_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecordMetaHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              recordMetaId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              subjectId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              subjectType_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              schemaUrl_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMetaHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMetaHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.class, axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.Builder.class);
    }

    public static final int RECORD_META_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object recordMetaId_;
    /**
     * <pre>
     * The unique record meta ID
     * </pre>
     *
     * <code>string record_meta_id = 2;</code>
     */
    public java.lang.String getRecordMetaId() {
      java.lang.Object ref = recordMetaId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordMetaId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The unique record meta ID
     * </pre>
     *
     * <code>string record_meta_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRecordMetaIdBytes() {
      java.lang.Object ref = recordMetaId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordMetaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object subjectId_;
    /**
     * <pre>
     * The unique subject ID
     * </pre>
     *
     * <code>string subject_id = 3;</code>
     */
    public java.lang.String getSubjectId() {
      java.lang.Object ref = subjectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The unique subject ID
     * </pre>
     *
     * <code>string subject_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectIdBytes() {
      java.lang.Object ref = subjectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_TYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object subjectType_;
    /**
     * <pre>
     * The unique subject type ID
     * </pre>
     *
     * <code>string subject_type = 4;</code>
     */
    public java.lang.String getSubjectType() {
      java.lang.Object ref = subjectType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The unique subject type ID
     * </pre>
     *
     * <code>string subject_type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectTypeBytes() {
      java.lang.Object ref = subjectType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHEMA_URL_FIELD_NUMBER = 5;
    private volatile java.lang.Object schemaUrl_;
    /**
     * <pre>
     * The url where the schema is located
     * </pre>
     *
     * <code>string schema_url = 5;</code>
     */
    public java.lang.String getSchemaUrl() {
      java.lang.Object ref = schemaUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The url where the schema is located
     * </pre>
     *
     * <code>string schema_url = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaUrlBytes() {
      java.lang.Object ref = schemaUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
     * </pre>
     *
     * <code>string timestamp = 6;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
     * </pre>
     *
     * <code>string timestamp = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRecordMetaIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, recordMetaId_);
      }
      if (!getSubjectIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subjectId_);
      }
      if (!getSubjectTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, subjectType_);
      }
      if (!getSchemaUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, schemaUrl_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRecordMetaIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, recordMetaId_);
      }
      if (!getSubjectIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subjectId_);
      }
      if (!getSubjectTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, subjectType_);
      }
      if (!getSchemaUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, schemaUrl_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof axoom.recordmetas.v1.Recordmetas.RecordMetaHeader)) {
        return super.equals(obj);
      }
      axoom.recordmetas.v1.Recordmetas.RecordMetaHeader other = (axoom.recordmetas.v1.Recordmetas.RecordMetaHeader) obj;

      boolean result = true;
      result = result && getRecordMetaId()
          .equals(other.getRecordMetaId());
      result = result && getSubjectId()
          .equals(other.getSubjectId());
      result = result && getSubjectType()
          .equals(other.getSubjectType());
      result = result && getSchemaUrl()
          .equals(other.getSchemaUrl());
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RECORD_META_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRecordMetaId().hashCode();
      hash = (37 * hash) + SUBJECT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSubjectId().hashCode();
      hash = (37 * hash) + SUBJECT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSubjectType().hashCode();
      hash = (37 * hash) + SCHEMA_URL_FIELD_NUMBER;
      hash = (53 * hash) + getSchemaUrl().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(axoom.recordmetas.v1.Recordmetas.RecordMetaHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code axoom.recordmetas.v1.RecordMetaHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:axoom.recordmetas.v1.RecordMetaHeader)
        axoom.recordmetas.v1.Recordmetas.RecordMetaHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMetaHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMetaHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.class, axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.Builder.class);
      }

      // Construct using axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        recordMetaId_ = "";

        subjectId_ = "";

        subjectType_ = "";

        schemaUrl_ = "";

        timestamp_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return axoom.recordmetas.v1.Recordmetas.internal_static_axoom_recordmetas_v1_RecordMetaHeader_descriptor;
      }

      public axoom.recordmetas.v1.Recordmetas.RecordMetaHeader getDefaultInstanceForType() {
        return axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.getDefaultInstance();
      }

      public axoom.recordmetas.v1.Recordmetas.RecordMetaHeader build() {
        axoom.recordmetas.v1.Recordmetas.RecordMetaHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public axoom.recordmetas.v1.Recordmetas.RecordMetaHeader buildPartial() {
        axoom.recordmetas.v1.Recordmetas.RecordMetaHeader result = new axoom.recordmetas.v1.Recordmetas.RecordMetaHeader(this);
        result.recordMetaId_ = recordMetaId_;
        result.subjectId_ = subjectId_;
        result.subjectType_ = subjectType_;
        result.schemaUrl_ = schemaUrl_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof axoom.recordmetas.v1.Recordmetas.RecordMetaHeader) {
          return mergeFrom((axoom.recordmetas.v1.Recordmetas.RecordMetaHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(axoom.recordmetas.v1.Recordmetas.RecordMetaHeader other) {
        if (other == axoom.recordmetas.v1.Recordmetas.RecordMetaHeader.getDefaultInstance()) return this;
        if (!other.getRecordMetaId().isEmpty()) {
          recordMetaId_ = other.recordMetaId_;
          onChanged();
        }
        if (!other.getSubjectId().isEmpty()) {
          subjectId_ = other.subjectId_;
          onChanged();
        }
        if (!other.getSubjectType().isEmpty()) {
          subjectType_ = other.subjectType_;
          onChanged();
        }
        if (!other.getSchemaUrl().isEmpty()) {
          schemaUrl_ = other.schemaUrl_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        axoom.recordmetas.v1.Recordmetas.RecordMetaHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (axoom.recordmetas.v1.Recordmetas.RecordMetaHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object recordMetaId_ = "";
      /**
       * <pre>
       * The unique record meta ID
       * </pre>
       *
       * <code>string record_meta_id = 2;</code>
       */
      public java.lang.String getRecordMetaId() {
        java.lang.Object ref = recordMetaId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordMetaId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The unique record meta ID
       * </pre>
       *
       * <code>string record_meta_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRecordMetaIdBytes() {
        java.lang.Object ref = recordMetaId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordMetaId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The unique record meta ID
       * </pre>
       *
       * <code>string record_meta_id = 2;</code>
       */
      public Builder setRecordMetaId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordMetaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique record meta ID
       * </pre>
       *
       * <code>string record_meta_id = 2;</code>
       */
      public Builder clearRecordMetaId() {
        
        recordMetaId_ = getDefaultInstance().getRecordMetaId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique record meta ID
       * </pre>
       *
       * <code>string record_meta_id = 2;</code>
       */
      public Builder setRecordMetaIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordMetaId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subjectId_ = "";
      /**
       * <pre>
       * The unique subject ID
       * </pre>
       *
       * <code>string subject_id = 3;</code>
       */
      public java.lang.String getSubjectId() {
        java.lang.Object ref = subjectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subjectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The unique subject ID
       * </pre>
       *
       * <code>string subject_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectIdBytes() {
        java.lang.Object ref = subjectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subjectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The unique subject ID
       * </pre>
       *
       * <code>string subject_id = 3;</code>
       */
      public Builder setSubjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subjectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique subject ID
       * </pre>
       *
       * <code>string subject_id = 3;</code>
       */
      public Builder clearSubjectId() {
        
        subjectId_ = getDefaultInstance().getSubjectId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique subject ID
       * </pre>
       *
       * <code>string subject_id = 3;</code>
       */
      public Builder setSubjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subjectId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subjectType_ = "";
      /**
       * <pre>
       * The unique subject type ID
       * </pre>
       *
       * <code>string subject_type = 4;</code>
       */
      public java.lang.String getSubjectType() {
        java.lang.Object ref = subjectType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subjectType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The unique subject type ID
       * </pre>
       *
       * <code>string subject_type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectTypeBytes() {
        java.lang.Object ref = subjectType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subjectType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The unique subject type ID
       * </pre>
       *
       * <code>string subject_type = 4;</code>
       */
      public Builder setSubjectType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subjectType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique subject type ID
       * </pre>
       *
       * <code>string subject_type = 4;</code>
       */
      public Builder clearSubjectType() {
        
        subjectType_ = getDefaultInstance().getSubjectType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique subject type ID
       * </pre>
       *
       * <code>string subject_type = 4;</code>
       */
      public Builder setSubjectTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subjectType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object schemaUrl_ = "";
      /**
       * <pre>
       * The url where the schema is located
       * </pre>
       *
       * <code>string schema_url = 5;</code>
       */
      public java.lang.String getSchemaUrl() {
        java.lang.Object ref = schemaUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schemaUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The url where the schema is located
       * </pre>
       *
       * <code>string schema_url = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaUrlBytes() {
        java.lang.Object ref = schemaUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The url where the schema is located
       * </pre>
       *
       * <code>string schema_url = 5;</code>
       */
      public Builder setSchemaUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schemaUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The url where the schema is located
       * </pre>
       *
       * <code>string schema_url = 5;</code>
       */
      public Builder clearSchemaUrl() {
        
        schemaUrl_ = getDefaultInstance().getSchemaUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The url where the schema is located
       * </pre>
       *
       * <code>string schema_url = 5;</code>
       */
      public Builder setSchemaUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schemaUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
       * </pre>
       *
       * <code>string timestamp = 6;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
       * </pre>
       *
       * <code>string timestamp = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
       * </pre>
       *
       * <code>string timestamp = 6;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
       * </pre>
       *
       * <code>string timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted (Example: 1972-01-01T10:00:20.021Z07:00).
       * </pre>
       *
       * <code>string timestamp = 6;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:axoom.recordmetas.v1.RecordMetaHeader)
    }

    // @@protoc_insertion_point(class_scope:axoom.recordmetas.v1.RecordMetaHeader)
    private static final axoom.recordmetas.v1.Recordmetas.RecordMetaHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new axoom.recordmetas.v1.Recordmetas.RecordMetaHeader();
    }

    public static axoom.recordmetas.v1.Recordmetas.RecordMetaHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecordMetaHeader>
        PARSER = new com.google.protobuf.AbstractParser<RecordMetaHeader>() {
      public RecordMetaHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecordMetaHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecordMetaHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordMetaHeader> getParserForType() {
      return PARSER;
    }

    public axoom.recordmetas.v1.Recordmetas.RecordMetaHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_recordmetas_v1_RecordMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_recordmetas_v1_RecordMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_recordmetas_v1_RecordMetaHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_recordmetas_v1_RecordMetaHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021recordmetas.proto\022\024axoom.recordmetas.v" +
      "1\"V\n\nRecordMeta\0227\n\007headers\030\001 \001(\0132&.axoom" +
      ".recordmetas.v1.RecordMetaHeader\022\017\n\007payl" +
      "oad\030\002 \001(\014\"{\n\020RecordMetaHeader\022\026\n\016record_" +
      "meta_id\030\002 \001(\t\022\022\n\nsubject_id\030\003 \001(\t\022\024\n\014sub" +
      "ject_type\030\004 \001(\t\022\022\n\nschema_url\030\005 \001(\t\022\021\n\tt" +
      "imestamp\030\006 \001(\tB0Z.gitlab.axoom.tech/iot/" +
      "go-rillaz/recordmetas/v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_axoom_recordmetas_v1_RecordMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_axoom_recordmetas_v1_RecordMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_recordmetas_v1_RecordMeta_descriptor,
        new java.lang.String[] { "Headers", "Payload", });
    internal_static_axoom_recordmetas_v1_RecordMetaHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_axoom_recordmetas_v1_RecordMetaHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_recordmetas_v1_RecordMetaHeader_descriptor,
        new java.lang.String[] { "RecordMetaId", "SubjectId", "SubjectType", "SchemaUrl", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
