// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filter/v1/filter.proto

package axoom.filters.v1;

public final class Filter {
  private Filter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StringPropertyFilterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axoom.filters.v1.StringPropertyFilter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The filter operation
     * </pre>
     *
     * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
     */
    int getOperationValue();
    /**
     * <pre>
     * The filter operation
     * </pre>
     *
     * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
     */
    axoom.filters.v1.Filter.StringPropertyFilter.Operation getOperation();

    /**
     * <pre>
     * Value of the operator
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <pre>
     * Value of the operator
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * <pre>
   * A filter for string properties
   * </pre>
   *
   * Protobuf type {@code axoom.filters.v1.StringPropertyFilter}
   */
  public  static final class StringPropertyFilter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:axoom.filters.v1.StringPropertyFilter)
      StringPropertyFilterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StringPropertyFilter.newBuilder() to construct.
    private StringPropertyFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StringPropertyFilter() {
      operation_ = 0;
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StringPropertyFilter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              operation_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_StringPropertyFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_StringPropertyFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              axoom.filters.v1.Filter.StringPropertyFilter.class, axoom.filters.v1.Filter.StringPropertyFilter.Builder.class);
    }

    /**
     * <pre>
     * The operation used to the filter the string property and the value
     * </pre>
     *
     * Protobuf enum {@code axoom.filters.v1.StringPropertyFilter.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      UNSPECIFIED(0),
      /**
       * <pre>
       * The string property matches the value
       * </pre>
       *
       * <code>EQUALS = 1;</code>
       */
      EQUALS(1),
      /**
       * <pre>
       * The string property does not match the value
       * </pre>
       *
       * <code>NOT_EQUALS = 2;</code>
       */
      NOT_EQUALS(2),
      /**
       * <pre>
       * The string property contains the value as substring
       * </pre>
       *
       * <code>CONTAINS = 3;</code>
       */
      CONTAINS(3),
      /**
       * <pre>
       * The string property matches one of the comma separated substrings provided as value
       * </pre>
       *
       * <code>ONE_OF = 4;</code>
       */
      ONE_OF(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      public static final int UNSPECIFIED_VALUE = 0;
      /**
       * <pre>
       * The string property matches the value
       * </pre>
       *
       * <code>EQUALS = 1;</code>
       */
      public static final int EQUALS_VALUE = 1;
      /**
       * <pre>
       * The string property does not match the value
       * </pre>
       *
       * <code>NOT_EQUALS = 2;</code>
       */
      public static final int NOT_EQUALS_VALUE = 2;
      /**
       * <pre>
       * The string property contains the value as substring
       * </pre>
       *
       * <code>CONTAINS = 3;</code>
       */
      public static final int CONTAINS_VALUE = 3;
      /**
       * <pre>
       * The string property matches one of the comma separated substrings provided as value
       * </pre>
       *
       * <code>ONE_OF = 4;</code>
       */
      public static final int ONE_OF_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operation valueOf(int value) {
        return forNumber(value);
      }

      public static Operation forNumber(int value) {
        switch (value) {
          case 0: return UNSPECIFIED;
          case 1: return EQUALS;
          case 2: return NOT_EQUALS;
          case 3: return CONTAINS;
          case 4: return ONE_OF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return axoom.filters.v1.Filter.StringPropertyFilter.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:axoom.filters.v1.StringPropertyFilter.Operation)
    }

    public static final int OPERATION_FIELD_NUMBER = 1;
    private int operation_;
    /**
     * <pre>
     * The filter operation
     * </pre>
     *
     * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <pre>
     * The filter operation
     * </pre>
     *
     * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
     */
    public axoom.filters.v1.Filter.StringPropertyFilter.Operation getOperation() {
      @SuppressWarnings("deprecation")
      axoom.filters.v1.Filter.StringPropertyFilter.Operation result = axoom.filters.v1.Filter.StringPropertyFilter.Operation.valueOf(operation_);
      return result == null ? axoom.filters.v1.Filter.StringPropertyFilter.Operation.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <pre>
     * Value of the operator
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Value of the operator
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (operation_ != axoom.filters.v1.Filter.StringPropertyFilter.Operation.UNSPECIFIED.getNumber()) {
        output.writeEnum(1, operation_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (operation_ != axoom.filters.v1.Filter.StringPropertyFilter.Operation.UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof axoom.filters.v1.Filter.StringPropertyFilter)) {
        return super.equals(obj);
      }
      axoom.filters.v1.Filter.StringPropertyFilter other = (axoom.filters.v1.Filter.StringPropertyFilter) obj;

      boolean result = true;
      result = result && operation_ == other.operation_;
      result = result && getValue()
          .equals(other.getValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + operation_;
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.filters.v1.Filter.StringPropertyFilter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(axoom.filters.v1.Filter.StringPropertyFilter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A filter for string properties
     * </pre>
     *
     * Protobuf type {@code axoom.filters.v1.StringPropertyFilter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:axoom.filters.v1.StringPropertyFilter)
        axoom.filters.v1.Filter.StringPropertyFilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_StringPropertyFilter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_StringPropertyFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                axoom.filters.v1.Filter.StringPropertyFilter.class, axoom.filters.v1.Filter.StringPropertyFilter.Builder.class);
      }

      // Construct using axoom.filters.v1.Filter.StringPropertyFilter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        operation_ = 0;

        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_StringPropertyFilter_descriptor;
      }

      @java.lang.Override
      public axoom.filters.v1.Filter.StringPropertyFilter getDefaultInstanceForType() {
        return axoom.filters.v1.Filter.StringPropertyFilter.getDefaultInstance();
      }

      @java.lang.Override
      public axoom.filters.v1.Filter.StringPropertyFilter build() {
        axoom.filters.v1.Filter.StringPropertyFilter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public axoom.filters.v1.Filter.StringPropertyFilter buildPartial() {
        axoom.filters.v1.Filter.StringPropertyFilter result = new axoom.filters.v1.Filter.StringPropertyFilter(this);
        result.operation_ = operation_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof axoom.filters.v1.Filter.StringPropertyFilter) {
          return mergeFrom((axoom.filters.v1.Filter.StringPropertyFilter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(axoom.filters.v1.Filter.StringPropertyFilter other) {
        if (other == axoom.filters.v1.Filter.StringPropertyFilter.getDefaultInstance()) return this;
        if (other.operation_ != 0) {
          setOperationValue(other.getOperationValue());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        axoom.filters.v1.Filter.StringPropertyFilter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (axoom.filters.v1.Filter.StringPropertyFilter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int operation_ = 0;
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
       */
      public int getOperationValue() {
        return operation_;
      }
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
       */
      public Builder setOperationValue(int value) {
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
       */
      public axoom.filters.v1.Filter.StringPropertyFilter.Operation getOperation() {
        @SuppressWarnings("deprecation")
        axoom.filters.v1.Filter.StringPropertyFilter.Operation result = axoom.filters.v1.Filter.StringPropertyFilter.Operation.valueOf(operation_);
        return result == null ? axoom.filters.v1.Filter.StringPropertyFilter.Operation.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
       */
      public Builder setOperation(axoom.filters.v1.Filter.StringPropertyFilter.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.StringPropertyFilter.Operation operation = 1;</code>
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <pre>
       * Value of the operator
       * </pre>
       *
       * <code>string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Value of the operator
       * </pre>
       *
       * <code>string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Value of the operator
       * </pre>
       *
       * <code>string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Value of the operator
       * </pre>
       *
       * <code>string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Value of the operator
       * </pre>
       *
       * <code>string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:axoom.filters.v1.StringPropertyFilter)
    }

    // @@protoc_insertion_point(class_scope:axoom.filters.v1.StringPropertyFilter)
    private static final axoom.filters.v1.Filter.StringPropertyFilter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new axoom.filters.v1.Filter.StringPropertyFilter();
    }

    public static axoom.filters.v1.Filter.StringPropertyFilter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StringPropertyFilter>
        PARSER = new com.google.protobuf.AbstractParser<StringPropertyFilter>() {
      @java.lang.Override
      public StringPropertyFilter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringPropertyFilter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StringPropertyFilter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StringPropertyFilter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public axoom.filters.v1.Filter.StringPropertyFilter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeyValueFilterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:axoom.filters.v1.KeyValueFilter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The key to retrieve the first operand
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <pre>
     * The key to retrieve the first operand
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <pre>
     * The filter operation
     * </pre>
     *
     * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
     */
    int getOperationValue();
    /**
     * <pre>
     * The filter operation
     * </pre>
     *
     * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
     */
    axoom.filters.v1.Filter.KeyValueFilter.Operation getOperation();

    /**
     * <pre>
     * The value of the second operand
     * </pre>
     *
     * <code>string value = 3;</code>
     */
    java.lang.String getValue();
    /**
     * <pre>
     * The value of the second operand
     * </pre>
     *
     * <code>string value = 3;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * <pre>
   * A key value filter
   * </pre>
   *
   * Protobuf type {@code axoom.filters.v1.KeyValueFilter}
   */
  public  static final class KeyValueFilter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:axoom.filters.v1.KeyValueFilter)
      KeyValueFilterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KeyValueFilter.newBuilder() to construct.
    private KeyValueFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeyValueFilter() {
      key_ = "";
      operation_ = 0;
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValueFilter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              operation_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_KeyValueFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_KeyValueFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              axoom.filters.v1.Filter.KeyValueFilter.class, axoom.filters.v1.Filter.KeyValueFilter.Builder.class);
    }

    /**
     * <pre>
     * The operation used to compare the two values
     * </pre>
     *
     * Protobuf enum {@code axoom.filters.v1.KeyValueFilter.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      UNSPECIFIED(0),
      /**
       * <pre>
       * The value retrieved by the key matches the provided value
       * </pre>
       *
       * <code>EQUALS = 1;</code>
       */
      EQUALS(1),
      /**
       * <pre>
       * The value retrieved by the key does not match the provided value
       * </pre>
       *
       * <code>NOT_EQUALS = 2;</code>
       */
      NOT_EQUALS(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      public static final int UNSPECIFIED_VALUE = 0;
      /**
       * <pre>
       * The value retrieved by the key matches the provided value
       * </pre>
       *
       * <code>EQUALS = 1;</code>
       */
      public static final int EQUALS_VALUE = 1;
      /**
       * <pre>
       * The value retrieved by the key does not match the provided value
       * </pre>
       *
       * <code>NOT_EQUALS = 2;</code>
       */
      public static final int NOT_EQUALS_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operation valueOf(int value) {
        return forNumber(value);
      }

      public static Operation forNumber(int value) {
        switch (value) {
          case 0: return UNSPECIFIED;
          case 1: return EQUALS;
          case 2: return NOT_EQUALS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return axoom.filters.v1.Filter.KeyValueFilter.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:axoom.filters.v1.KeyValueFilter.Operation)
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <pre>
     * The key to retrieve the first operand
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The key to retrieve the first operand
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATION_FIELD_NUMBER = 2;
    private int operation_;
    /**
     * <pre>
     * The filter operation
     * </pre>
     *
     * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <pre>
     * The filter operation
     * </pre>
     *
     * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
     */
    public axoom.filters.v1.Filter.KeyValueFilter.Operation getOperation() {
      @SuppressWarnings("deprecation")
      axoom.filters.v1.Filter.KeyValueFilter.Operation result = axoom.filters.v1.Filter.KeyValueFilter.Operation.valueOf(operation_);
      return result == null ? axoom.filters.v1.Filter.KeyValueFilter.Operation.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object value_;
    /**
     * <pre>
     * The value of the second operand
     * </pre>
     *
     * <code>string value = 3;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The value of the second operand
     * </pre>
     *
     * <code>string value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (operation_ != axoom.filters.v1.Filter.KeyValueFilter.Operation.UNSPECIFIED.getNumber()) {
        output.writeEnum(2, operation_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (operation_ != axoom.filters.v1.Filter.KeyValueFilter.Operation.UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, operation_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof axoom.filters.v1.Filter.KeyValueFilter)) {
        return super.equals(obj);
      }
      axoom.filters.v1.Filter.KeyValueFilter other = (axoom.filters.v1.Filter.KeyValueFilter) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && operation_ == other.operation_;
      result = result && getValue()
          .equals(other.getValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + operation_;
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static axoom.filters.v1.Filter.KeyValueFilter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(axoom.filters.v1.Filter.KeyValueFilter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A key value filter
     * </pre>
     *
     * Protobuf type {@code axoom.filters.v1.KeyValueFilter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:axoom.filters.v1.KeyValueFilter)
        axoom.filters.v1.Filter.KeyValueFilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_KeyValueFilter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_KeyValueFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                axoom.filters.v1.Filter.KeyValueFilter.class, axoom.filters.v1.Filter.KeyValueFilter.Builder.class);
      }

      // Construct using axoom.filters.v1.Filter.KeyValueFilter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        operation_ = 0;

        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return axoom.filters.v1.Filter.internal_static_axoom_filters_v1_KeyValueFilter_descriptor;
      }

      @java.lang.Override
      public axoom.filters.v1.Filter.KeyValueFilter getDefaultInstanceForType() {
        return axoom.filters.v1.Filter.KeyValueFilter.getDefaultInstance();
      }

      @java.lang.Override
      public axoom.filters.v1.Filter.KeyValueFilter build() {
        axoom.filters.v1.Filter.KeyValueFilter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public axoom.filters.v1.Filter.KeyValueFilter buildPartial() {
        axoom.filters.v1.Filter.KeyValueFilter result = new axoom.filters.v1.Filter.KeyValueFilter(this);
        result.key_ = key_;
        result.operation_ = operation_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof axoom.filters.v1.Filter.KeyValueFilter) {
          return mergeFrom((axoom.filters.v1.Filter.KeyValueFilter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(axoom.filters.v1.Filter.KeyValueFilter other) {
        if (other == axoom.filters.v1.Filter.KeyValueFilter.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.operation_ != 0) {
          setOperationValue(other.getOperationValue());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        axoom.filters.v1.Filter.KeyValueFilter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (axoom.filters.v1.Filter.KeyValueFilter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <pre>
       * The key to retrieve the first operand
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The key to retrieve the first operand
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The key to retrieve the first operand
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The key to retrieve the first operand
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The key to retrieve the first operand
       * </pre>
       *
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private int operation_ = 0;
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
       */
      public int getOperationValue() {
        return operation_;
      }
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
       */
      public Builder setOperationValue(int value) {
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
       */
      public axoom.filters.v1.Filter.KeyValueFilter.Operation getOperation() {
        @SuppressWarnings("deprecation")
        axoom.filters.v1.Filter.KeyValueFilter.Operation result = axoom.filters.v1.Filter.KeyValueFilter.Operation.valueOf(operation_);
        return result == null ? axoom.filters.v1.Filter.KeyValueFilter.Operation.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
       */
      public Builder setOperation(axoom.filters.v1.Filter.KeyValueFilter.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The filter operation
       * </pre>
       *
       * <code>.axoom.filters.v1.KeyValueFilter.Operation operation = 2;</code>
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <pre>
       * The value of the second operand
       * </pre>
       *
       * <code>string value = 3;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The value of the second operand
       * </pre>
       *
       * <code>string value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The value of the second operand
       * </pre>
       *
       * <code>string value = 3;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The value of the second operand
       * </pre>
       *
       * <code>string value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The value of the second operand
       * </pre>
       *
       * <code>string value = 3;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:axoom.filters.v1.KeyValueFilter)
    }

    // @@protoc_insertion_point(class_scope:axoom.filters.v1.KeyValueFilter)
    private static final axoom.filters.v1.Filter.KeyValueFilter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new axoom.filters.v1.Filter.KeyValueFilter();
    }

    public static axoom.filters.v1.Filter.KeyValueFilter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeyValueFilter>
        PARSER = new com.google.protobuf.AbstractParser<KeyValueFilter>() {
      @java.lang.Override
      public KeyValueFilter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValueFilter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KeyValueFilter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValueFilter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public axoom.filters.v1.Filter.KeyValueFilter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_filters_v1_StringPropertyFilter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_filters_v1_StringPropertyFilter_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_axoom_filters_v1_KeyValueFilter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_axoom_filters_v1_KeyValueFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026filter/v1/filter.proto\022\020axoom.filters." +
      "v1\"\276\001\n\024StringPropertyFilter\022C\n\toperation" +
      "\030\001 \001(\01620.axoom.filters.v1.StringProperty" +
      "Filter.Operation\022\r\n\005value\030\002 \001(\t\"R\n\tOpera" +
      "tion\022\017\n\013UNSPECIFIED\020\000\022\n\n\006EQUALS\020\001\022\016\n\nNOT" +
      "_EQUALS\020\002\022\014\n\010CONTAINS\020\003\022\n\n\006ONE_OF\020\004\"\245\001\n\016" +
      "KeyValueFilter\022\013\n\003key\030\001 \001(\t\022=\n\toperation" +
      "\030\002 \001(\0162*.axoom.filters.v1.KeyValueFilter" +
      ".Operation\022\r\n\005value\030\003 \001(\t\"8\n\tOperation\022\017" +
      "\n\013UNSPECIFIED\020\000\022\n\n\006EQUALS\020\001\022\016\n\nNOT_EQUAL" +
      "S\020\002B+Z)gitlab.axoom.tech/iot/go-rillaz/f" +
      "ilter/v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_axoom_filters_v1_StringPropertyFilter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_axoom_filters_v1_StringPropertyFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_filters_v1_StringPropertyFilter_descriptor,
        new java.lang.String[] { "Operation", "Value", });
    internal_static_axoom_filters_v1_KeyValueFilter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_axoom_filters_v1_KeyValueFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_axoom_filters_v1_KeyValueFilter_descriptor,
        new java.lang.String[] { "Key", "Operation", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
